import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import Head from "next/head";

import Footer from "@/app/footer/Footer";
import Header from "@/app/header/Header";

import "./globals.css";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Galinfo",
  description: "Generated by create next app",
  icons: {
    icon: '/galinfo-favicon.svg',
  },
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <Head>
      <link
        rel="stylesheet"
        href="https://sinoptik.ua/resources/informer/css/informer.css"
      />
    </Head>
    <body className={`${openSans.variable} antialiased`}>
    <Header/>
    {children}
    <Footer/>
    </body>
    </html>
  );
}