import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import Link from "next/link";

import paths from "@/app/paths";

import "./globals.css";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${openSans.variable} antialiased`}>
      <header>
        <Link href={paths.society}>
          <button>Перейти на About</button>
        </Link>
      </header>
      {children}
      <footer>paka</footer>
    </body>
    </html>
  );
}